name: vaden_workspace
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - vaden
  - vaden/example
  - vaden_class_scanner
  - vaden_generator/backend
  - vaden_generator/frontend
  - packages/anaki_orm

