name: vaden
description: Dart backend project create by Flutterando community. Using and action!
version: 0.0.5
repository: https://github.com/Flutterando/vaden

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  auto_injector: ^2.1.0
  lucid_validation: ^1.2.5
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  yaml: ^3.1.3
  openapi_spec: ^0.7.26 
  shelf_swagger_ui: ^2.0.0
  shelf_static: ^1.1.3
  mime: ^1.0.6
  shelf_multipart: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
