name: example
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  vaden:
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner:
